version: "2"

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # Only recommended for development
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_DATABASE=dicourse
    volumes:
      - "postgresql_data:/bitnami/postgresql"

  redis:
    image: docker.io/bitnami/redis:6.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # Only recommended for development
    volumes:
      - "redis_data:/bitnami/discourse"

  discourse:
    image: docker.io/bitnami/discourse:2
    depends_on:
      - postgresql
      - redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # Only recommended for development
      - DISCOURSE_HOST=localhost
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=admin
      - DISCOURSE_DATABASE_NAME=dicourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=dicourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
    ports:
      - "80:3000"
    volumes:
      - "discourse_data:/bitnami/discourse"

  sidekiq:
    image: docker.io/bitnami/discourse:2
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    depends_on:
      - discourse
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # Only recommended for development
      - DISCOURSE_HOST=localhost
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=admin
      - DISCOURSE_DATABASE_NAME=dicourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
    volumes:
      - "sidekiq_data:/bitnami/discourse"

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
